#!/bin/sh
# Regenerates the chart's RBAC templates from the kubebuilder sources in
# config/rbac, wrapping each rules block in the Helm gate, name and labels the
# chart needs. With --check it only verifies they are current and exits 1 on
# drift; CI runs that. The chart's rules were ported by hand and drifted: the
# metrics-auth role was never ported at all, and nothing noticed.
set -eu

# Sources the chart deliberately does not ship, so a new file under
# config/rbac fails the check instead of being silently left out.
skip='metrics_reader_role.yaml migration_admin_role.yaml migration_editor_role.yaml migration_viewer_role.yaml'

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT
fail=0

# rules: runs to the end of every file controller-gen and kubebuilder write.
rules() {
  awk '/^rules:/{p=1} p' "$1"
}

emit() {
  src=config/rbac/$1

  case $2 in
  clusterrole.yaml)
    printf '{{- if .Values.rbac.create }}\n'
    printf '{{- /* Generated by hack/sync-chart-rbac.sh from %s. */}}\n' "$src"
    printf 'apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRole\n'
    printf 'metadata:\n  name: {{ include "pgcopydb-operator.fullname" . }}-manager\n'
    printf '  labels:\n    {{- include "pgcopydb-operator.labels" . | nindent 4 }}\n'
    rules "$src"
    printf '{{- end }}\n'
    ;;
  role.yaml)
    printf '{{- if and .Values.rbac.create .Values.leaderElection.enabled }}\n'
    printf '{{- /* Generated by hack/sync-chart-rbac.sh from %s. */}}\n' "$src"
    printf 'apiVersion: rbac.authorization.k8s.io/v1\nkind: Role\n'
    printf 'metadata:\n  name: {{ include "pgcopydb-operator.fullname" . }}-leader-election\n'
    printf '  labels:\n    {{- include "pgcopydb-operator.labels" . | nindent 4 }}\n'
    rules "$src"
    printf '{{- end }}\n'
    ;;
  metrics-auth-rbac.yaml)
    # Gated on metrics.enabled too: with no metrics endpoint the manager runs
    # no authn/authz filter, so the permission would grant nothing.
    printf '{{- if and .Values.rbac.create .Values.metrics.enabled }}\n'
    printf '{{- /* Generated by hack/sync-chart-rbac.sh from %s.\n' "$src"
    printf 'The secure metrics endpoint authenticates its scrapers itself: it sends\n'
    printf 'each caller'"'"'s token to the API server as a TokenReview and its access as\n'
    printf 'a SubjectAccessReview. */}}\n'
    printf 'apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRole\n'
    printf 'metadata:\n  name: {{ include "pgcopydb-operator.fullname" . }}-metrics-auth\n'
    printf '  labels:\n    {{- include "pgcopydb-operator.labels" . | nindent 4 }}\n'
    rules "$src"
    printf -- '---\n'
    printf 'apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRoleBinding\n'
    printf 'metadata:\n  name: {{ include "pgcopydb-operator.fullname" . }}-metrics-auth\n'
    printf '  labels:\n    {{- include "pgcopydb-operator.labels" . | nindent 4 }}\n'
    printf 'roleRef:\n  apiGroup: rbac.authorization.k8s.io\n  kind: ClusterRole\n'
    printf '  name: {{ include "pgcopydb-operator.fullname" . }}-metrics-auth\n'
    printf 'subjects:\n  - kind: ServiceAccount\n'
    printf '    name: {{ include "pgcopydb-operator.serviceAccountName" . }}\n'
    printf '    namespace: {{ .Release.Namespace }}\n'
    printf '{{- end }}\n'
    ;;
  esac
}

sync() {
  src=config/rbac/$1
  dst=charts/pgcopydb-operator/templates/$2

  if [ ! -f "$src" ]; then
    echo "$src is missing: hack/sync-chart-rbac.sh expects it" >&2
    exit 1
  fi
  emit "$1" "$2" > "$tmp"

  if [ "$mode" = check ]; then
    if ! diff -q "$tmp" "$dst" >/dev/null 2>&1; then
      echo "$dst has drifted from $src: run hack/sync-chart-rbac.sh and commit" >&2
      diff -u "$dst" "$tmp" 2>&1 | head -40 >&2 || true
      fail=1
    else
      echo "$dst is current with $src"
    fi
  else
    cp "$tmp" "$dst"
    echo "$dst regenerated from $src"
  fi
}

mode=sync
[ "${1:-}" = "--check" ] && mode=check

sync role.yaml clusterrole.yaml
sync leader_election_role.yaml role.yaml
sync metrics_auth_role.yaml metrics-auth-rbac.yaml

# Every Role and ClusterRole under config/rbac has to be generated above or
# named in $skip. Keyed on kind rather than on kubebuilder's *_role.yaml
# filename, so a role that arrives in a differently named file still has to be
# accounted for. This is the assertion the original omission needed: a role
# nobody ported fails here instead of shipping missing.
for f in config/rbac/*.yaml; do
  grep -qE '^kind: (Cluster)?Role$' "$f" || continue
  base=${f##*/}
  case " role.yaml leader_election_role.yaml metrics_auth_role.yaml $skip " in
  *" $base "*) continue ;;
  esac
  echo "$f defines a role the chart neither renders nor lists as skipped in $0" >&2
  fail=1
done

if [ "$fail" -ne 0 ]; then
  exit 1
fi
